default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: doximity
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: dox_blog_development

test:
  <<: *default
  database: dox_blog
