default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: dox_blog_development

test:
  <<: *default
  database: dox_blog

production:
  <<: *default
  database: dox_blog
  url: <%= ENV['DATABASE_URL'] %>